### ISSUE TITLE
Possible Error in piped expressions

### ISSUE THREAD

**Issue by thomasjwood** [ddotta/cookbook-rpolars#18]
On this [page](https://ddotta.github.io/cookbook-rpolars/first_steps.html), this function:

`pl$col("bar")$filter(pl.col("foo") == 1)$sum()`

should actual be

`pl$col("bar")$filter(pl$col("foo") == 1)$sum()`

I think? (I'm still new to `polars`, so apologies if I missed something!)

**Comment by ddotta** [comment]
You're right @thomasjwood! Thanks for you issue, I'll fix it!
