### ISSUE TITLE
2.4 Filter rows

### ISSUE THREAD

**Issue by emaleckova** [ddotta/cookbook-rpolars#33]
First of all, thanks for a great cookbook - I really enjoy following it along and trying the code out. However, I am a bit confused about the [2.4 Filter rows section](https://ddotta.github.io/cookbook-rpolars/data_manipulation.html#filter-rows). The example code is as follows:
```
data(iris)
# The first four lines
pl$DataFrame(iris)[1:4]
```
which however does not seem to be row filtering but rather selection of columns based on their index. For row filtering, the code should be `pl$DataFrame(iris)[1:4, ]`.

**Comment by ddotta** [comment]
Many thanks @emaleckova for this issue ! It's fixed !
