### ISSUE TITLE
Benchmark comment "from a CSV"

### ISSUE THREAD

**Issue by phgrosjean** [ddotta/cookbook-rpolars#7]
Hello,

On your CSV benchmark, you use `read.csv()` (base function, very slow) for all three versions base/dplyr/data.table, while comparing to the Polars-specific CSV read function. Most of the time is spent in this function. So, the same timings for all three that is not representative of each implementation because tidyverse would use `readr::read_csv()` and data.table would use `fread()` instead.

Also, in your comparison between eager and lazy polars, you forgot to `collect()` the lazy version. It should be: 

```
microbenchmark(
  "eager mode" = csv_eager_polars(),
  "lazy mode" = csv_lazy_polars()$collect(),
  times = 5
 )
```

Otherwise, excellent work !

PhG

**Comment by ddotta** [comment]
Hi @phgrosjean,  
You're right, I'll correct that and post the new benchmark results in this issue.  
Thanks for the feedback!

**Comment by ddotta** [comment]
I've made the corrections and while we wait for the book to become available again, here are the results on my computer:

![image](https://github.com/ddotta/cookbook-rpolars/assets/13397519/014f9739-a456-4fa8-891a-9c5a8aac50c5)


![image](https://github.com/ddotta/cookbook-rpolars/assets/13397519/6eb530e2-6f69-4178-92ce-92a4946c4851)
